version: '3.1'

services:

  nginx:
    image: nginx
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - notitas_auth

  notitas_auth:
    build: ./
    container_name: notitas_auth
    tty: true
    ports:
      - 3000:3000
    environment:
      TZ: America/Hermosillo
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      notitas_pg_db:
        condition: service_healthy
    command: sh -c "npm run dev"

  notitas_pg_db:
    image: postgres:15.2
    container_name: notitas_pg_db
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: notitas
      TZ: America/Hermosillo
    volumes:
      - ./DB/postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    environment:
      TZ: America/Hermosillo
    ports:
      - 8080:8080
    depends_on:
      notitas_pg_db:
        condition: service_started